name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.1.0
        with:
          # Yarn command
          cmd: install
          
      - name: Creating build
        run: sudo yarn build - SLUG=$(echo ${CI_BUILD_REFNAME} | sed 's/[^a-zA-Z0-9-]/-/g ; s/-+/-/g')
          
      - name: installing surge
        run: npm install -g surge
          
      - name: deploying on surge
        run: surge ./build  animation_app.surge.sh --token ${{secrets.SURGE_TOKEN}}
